### PR TITLE
feat: add support to parse of type parameters

### PR DESCRIPTION
**Pull request by kawaemon**
This PR adds support to parse of type parameters syntax, which will be added on Go 1.18.

TODO:
- [ ] Reduce conflicts section.
- [x] Regenerate and commit new parser.

Checklist:
- [x] All tests pass in CI.
- [x] There are sufficient tests for the new fix/feature.
- [x] Grammar rules have not been renamed unless absolutely necessary.
- [ ] The conflicts section hasn't grown too much.
  5 → 11. It's grown very much. I tried but I couldn't reduce it. Would you give me an advice?
- [x] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).
  1182 → 1220. I think it's reasonable.

### CODE REVIEW

**Comment by aryx** [comment]
Lgtm!
There are indeed a few more conflicts, but from what I remember adding generics to Java introduced
similar conflicts too.

**Comment by kawaemon** [comment]
I made tiny code quality change (72ffe0e) and updated highlight query. I think it's ready to merge now.

**Comment by aryx** [comment]
Can you rebase to fix the conflicts (now that I've merged your other PR)?

**Comment by aryx** [comment]
Those generated files in the repository are a bit annoying @maxbrunsfeld for reviewing and merging purposes. They generate extract conflicts. If people really need the parser.c, why we don't have separate repository with all those generated code. This would avoid having those huge PRs with thousands lines of code in parser.c that are not even inspected by humans. This also make the statistics on contributors useless.

**Comment by kawaemon** [comment]
Rebased and regenerated parser (to fix conflict). Should be fine.

**Review by aryx — APPROVED** [review]
Thx! This is great.

**Comment by kawaemon** [comment]
Thank you for reviews!

**Comment by maxbrunsfeld** [comment]
Yeah we have an item in Tree-sitter’s 1.0 roadmap issue about changing how we store the generated files, but nobody is working on it right now. It’s going to take a bit of effort to design and set up the automation, and get the community migrated away from using the git repositories directly.

**Comment by aryx** [comment]
ok, got it

**Pull request merged**
