### PR TITLE
Added format verbs

### PR DESCRIPTION
**Pull request by konart**
Related go docs: https://pkg.go.dev/fmt#hdr-Printing

I really wanted this feature and https://github.com/tree-sitter/tree-sitter-go/pull/85 seems to be kind of stale so I did my best attempt here.

`_interpreted_string_literal_percent_sign` seems like a hack but I haven't figured any other way to tell tree-sitter to treat `%` just as part of a string literal in one special case (when`%` is at the end of the string).

The other thing I haven't figured out is highlights.scm. When trying to install local go TS with `TSInstall` newly added hls do not get applied (and in fact the structure of `~/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/go/highlights.scm` is quite different. Am I doing it wrong?

I've added related test to `literals` and removed format verb from `statements`.

This PR does cover all format verbs cases in an `interpreted_string_literal` but does not cover different usecases for the literal. (using it as an argument to `fmt.Println` etc. makes format verbs useless)

Checklist:
- [x] All tests pass in CI.
- [x] There are sufficient tests for the new fix/feature.
- [x] Grammar rules have not been renamed unless absolutely necessary.
- [x] The conflicts section hasn't grown too much.
- [x] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

### CODE REVIEW

**Comment by ameddin73** [comment]
Great work, hope this feature gets merged soon!

**Comment by bstncartwright** [comment]
Also very excited for this!

**Comment by maxbrunsfeld** [comment]
I don't think that Tree-sitter should parse these format verbs. They aren't part of the string literal's syntax; they're just a pattern that the `Printf` family of functions looks for. For syntax-highlighting these things, I think it would be better to handle it with some kind of separate layer of logic, like language injections.

**Comment by matoous** [comment]
I think highlighting the printf format is fine. The format verbs are basically different kind of escape sequences and those are already captured. The decision is easier for languages with string interpolation (e.g. javascript with `${}`).

Linking this as another place where this was discussed: https://github.com/nvim-treesitter/nvim-treesitter/issues/2917

**Comment by amaanq** [comment]
FWIW this would greatly benefit editors to easily distinguish format verbs and highlight them differently, rather than rely on injections/regex-based matching.

I too would love to see this merged

**Comment by konart** [comment]
FYI 

https://github.com/nvim-treesitter/nvim-treesitter/issues/2917
https://github.com/nvim-treesitter/nvim-treesitter/commit/f2119df35cdcdb0c6c9bf791a04000d4d131cef7

**Pull request closed without merging**
