### PR TITLE
Allow GenericType to accept QualifiedType

### PR DESCRIPTION
**Pull request by kawaemon**
Current parser does not accept this code since GenericType does not accept QualifiedType: 
```go
func g2(a foo.bar[int]) {}
```

This PR fixes this behaviour.

Checklist:
- [ ] All tests pass in CI.
- [x] There are sufficient tests for the new fix/feature.
- [x] Grammar rules have not been renamed unless absolutely necessary.
- [x] The conflicts section hasn't grown too much.
- [x] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).
1257 -> 1269

### CODE REVIEW

**Comment by aryx** [comment]
@dcreager @maxbrunsfeld something changed recently regarding CI? There's no CI check jobs running anymore ...

**Comment by kawaemon** [comment]
@aryx 
Looks like current CI doesn't run against pull requests. This file is written about 2 years ago, so this is not recent change.
It's not running on other PRs as well.
https://github.com/tree-sitter/tree-sitter-go/blob/13418148805c8cb50abbdfae779a59bde8fec901/.github/workflows/ci.yml#L2-L5

**Comment by kawaemon** [comment]
I think adding "pull_request" event here will fix this problem anyway.
https://github.com/tree-sitter/tree-sitter-go/blob/13418148805c8cb50abbdfae779a59bde8fec901/.github/workflows/ci.yml#L2-L5

**Comment by aryx** [comment]
@dcreager @maxbrunsfeld any idea why CI does not kick in anymore for those PRs?
This seriously limit our ability to merge external PRs.

**Comment by aryx** [comment]
I need this fix in semgrep, so I'll merge, but someone need to figure out why the CI checks do not run here anymore.

**Pull request merged**
