### PR TITLE
Upgrade to `tree-sitter` 0.21.0

### PR DESCRIPTION
**Pull request by smoelius**
Is there anything holding this back?

If there is, sorry for the noise.

### CODE REVIEW

**Comment by amaanq** [comment]
No not at all, sorry for being behind, I've been updating the grammar repos now though. Will do this in my own pr that updates a lot of other stuff too (new language bindings/updating other build files)

**Comment by smoelius** [comment]
Thank you for the reply, @amaanq.

Shortly after I opened this PR, I noticed that `tree-sitter` 0.22 was released.

But it looks like #139 upgrades `tree-sitter-go` to just `tree-sitter` 0.21.

Is this intentional? If so, can I ask why?

**Comment by amaanq** [comment]
yeah, we're going to be getting rid of the need for tree-sitter (https://github.com/tree-sitter/tree-sitter/pull/3069) since it has been somewhat annoying when the core library updates and every downstream grammar has to as well

for now, the solution is to just specify >= 0.21.0, which is compatible with 0.22 as well.

**Comment by smoelius** [comment]
> for now, the solution is to just specify >= 0.21.0, which is compatible with 0.22 as well.

Today I learned! Thanks!

**Pull request closed without merging**
