### PR TITLE
feat(grammar): capture comment directives

### PR DESCRIPTION
**Pull request by matoous**
Adds additional capture group for comment directives. The purpose is to allow editors relying on tree-sitter for higlight to provide different higlight for directive comments that fullfil other than documenting purpose in the code.

The syntax of the directive comments is described in the [syntax](https://tip.golang.org/doc/comment#syntax) section of the _comment_ documentation.

Checklist:
- [ ] All tests pass in CI.
- [ ] There are sufficient tests for the new fix/feature.
- [x] Grammar rules have not been renamed unless absolutely necessary.
- [x] The conflicts section hasn't grown too much.
- [x] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

### CODE REVIEW

**Review by aryx — APPROVED** [review]

**Comment by matoous** [comment]
@aryx sorry, seems like my change didn't pass the pipeline: https://github.com/tree-sitter/tree-sitter-go/actions/runs/3628335707/jobs/6119224709. I didn't notice these tests. I can prepare revert if necessary (and will take a look at the changes one more time).

**Comment by aryx** [comment]
yes please send a revert PR

**Comment by aryx** [comment]
also @dcreager @maxbrunsfeld why those github actions are not run on the PR itself?

**Comment by aryx** [comment]
It used to work ... who changed it?

**Pull request merged**
