### PR TITLE
Add support for go.mod files

### PR DESCRIPTION
**Pull request by camdencheek**
This commit adds a grammar for go.mod files using the definition found
at https://golang.org/ref/mod#go-mod-file-grammar.

I did my best to imitate the multi-grammar repos for [typescript](https://github.com/tree-sitter/tree-sitter-typescript) and [ocaml](https://github.com/tree-sitter/tree-sitter-ocaml), but I may have missed some things. 

I've been using this through [`nvim-treesitter`](https://github.com/nvim-treesitter/nvim-treesitter) (screenshot below), so I haven't exercised the other bindings. 

Screen Shot 2021-04-05 at 16 16 08

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
This is great work @camdencheek. I actually think that the mult-grammar repository structure of `tree-sitter-typescript` and `tree-sitter-ocaml` is a bit cumbersome, and it's only worthwhile to me because those grammars *share* some common code. For example, in TypeScript, the `typescript` and `tsx` grammars share some common grammar code, queries, and tests.

In this case, since `go.mod` and Go are two completely different languages, and some users may only care about Go, but not go.mod, I would prefer to just keep the `go.mod` grammar in  its own repository. What do you think about that?

**Comment by camdencheek** [comment]
Seems reasonable to me! I'll go ahead and pull it out into a separate repo. 

What are your thoughts on this being a personal repo vs under the tree-sitter org? I don't see anything in the contribution guide about contributing new grammars. I'm happy to maintain it either way.

**Comment by camdencheek** [comment]
Closing in favor of implementing the go.mod grammar in a separate repo. New repo is at https://github.com/camdencheek/tree-sitter-go-mod

**Comment by maxbrunsfeld** [comment]
Yeah, I think a personal repo is best. Do you want to open a PR on `tree-sitter/tree-sitter` that adds a link to your grammar in the docs ([here](https://github.com/tree-sitter/tree-sitter/blob/master/docs/index.md))?

**Comment by camdencheek** [comment]
[Done](https://github.com/tree-sitter/tree-sitter/pull/1079) 👍

**Pull request closed without merging**
