### PR TITLE
Update to only highlight var declarations

### PR DESCRIPTION
**Pull request by mikelu92**
See https://github.com/ubolonton/emacs-tree-sitter/issues/155 for context
Checklist:
- [ ] All tests pass in CI.
- [ ] There are sufficient tests for the new fix/feature.
- [x] Grammar rules have not been renamed unless absolutely necessary.
- [x] The conflicts section hasn't grown too much.
- [x] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
In these highlights, we want variables to be highlighted the same in all places that they appear (so that usages match their declaration site), so I don't think we'd want to change this. Maybe you could add these special rules just in your emacs config?

**Comment by mikelu92** [comment]
that differs from uboloton's comment here: https://github.com/ubolonton/emacs-tree-sitter/issues/155#issuecomment-886021434

I already changed it in my own config, just thought that this was something that was what it's supposed to be everywhere?

**Comment by ubolonton** [comment]
These are specific to the Emacs package `tree-sitter-langs`, so the changes should be made against [this file](https://github.com/ubolonton/tree-sitter-langs/blob/master/queries/go/highlights.scm) instead.

**Comment by mikelu92** [comment]
gotcha my mistake!

**Pull request closed without merging**
